# Generated by Django 3.2.15 on 2022-08-28 10:49

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_rooms_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True, null=True), default=[datetime.time(12, 0)], size=None),
            preserve_default=False,
        ),
    ]
