# Generated by Django 3.2.15 on 2022-08-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('date_selected', models.DateField(blank=True, null=True)),
                ('time_selected', models.TimeField(blank=True, null=True)),
                ('booking_type', models.IntegerField(choices=[(0, 'Customer Booked'), (1, 'Management Blocked')], default=0)),
                ('room_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
