# Generated by Django 3.2.15 on 2022-09-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('date_selected', 'time_selected')},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-status',)},
        ),
    ]
